---
framework: jest
preRun:
  command:
    - npm i -g pnpm@$7.2.1
    - npm run build
preMerge:
  env:
    TRACE_PLAYWRIGHT: true
    HEADLESS: true
  pattern:
    - 'test/unit/**/*.test.{js,ts,tsx}'
postMerge:
  env:
    TRACE_PLAYWRIGHT: true
    HEADLESS: true
  pattern:
    - 'test/unit/**/*.test.{js,ts,tsx}'
postRun:
  command:
    - node --version
version: 1.0.0
parallelism: 2
splitMode: file
