---
framework: jest
postMerge:
  pattern:
    - 'test/unit/**/*.test.ts'
preMerge:
  pattern:
    - 'test/unit/**/*.test.{js,ts,tsx}'
preRun:
  command:
    - yarn
postRun:
  command:
    - yarn --version
version: 1.0

